class Config_strings():
    exit = "exit"
    cont = "continue"
    list_start = "\tToday we have:"
    will_have = "\tProbably we will have these soon:\t\t"
    out_of_these = "\tSorry, we are out of these:\t\t"
    create_order_greetings = "\tI need vendor code and amount (xxxx <amount>) \n\tType exit if you're ready"
    dont_have = "\tWe don't have so much or we don't have that at all! Try again or print exit"
    order_looks = "\tNow your order looks so: \n {} \n\tType exit if you're ready"
    too_much = "too_much_items"
    more_than_possible = "Somehow you decided to buy more than possible :("
    order_id = "\tYour order ID is {}"
    get_status_greetings = "\tType ID or exit"
    works = "works"
    online = "We are online! \n"
    smth_wrong = "Something is wrong with connection \n"
    bad_connection = "Connection gone wrong"
    main_greetings = ("Type one of these commads: \n"
                      "status -- take status of your order \n"
                      "create -- create new order \n"
                      "store -- ask for what we have in our store \n"
                      "exit -- exit")
    command = "Enter command>"
    status = "status"
    create = "create"
    store = "store"
    bad_input = "Bad input.Try again"