class Config_strings():
    change_store_greetings = "\tOkay! Enter vendor code and amount (xxxx <amount>) \n As always exit to exit"
    exit = "exit"
    cont = "continue"
    id = "id"
    value = "value"
    order_looks = "\tNow it looks so: \n {} \n Exit if ready"
    change_status_greetings = "\tType ID and +-value or exit"
    bad_input = "Bad input.Try again"
    done = "Done!"
    mail_greetings = "\tType ID or exit"
    test = "works"
    connected = "online"
    connected_to_the_wrong_service = "Kinda strange. Don't know where, but we are online"
    ask_politely = "What we gonna do today?"
    main_greetings = ("\tchange store -- add or delete goods \n"
                      "\tchange status -- change order status \n"
                      "\tmail -- write polite letter about the loss of goods \n"
                      "\texit")
    command = "Enter command>"
    change_store = "change store"
    change_status = "change status"
    mail = "mail"
